name       : bumpversion
version    : 0.5.3
release    : 1
source     :
    - https://github.com/lbryio/bumpversion/archive/v0.5.3.tar.gz : 97ac6efca7544853309b68efe92f113ab6bddb77ecbaefa5702a6183a30bcb33
license    : MIT
component  : system.utils
summary    : Version-bump your software with a single command!
description: |
    A small command line tool to simplify releasing software by updating all version strings in your source code by the correct increment.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
