name       : bumpversion
version    : 1.0.0
release    : 3
source     :
    - https://github.com/c4urself/bump2version/archive/v1.0.0.tar.gz : 06a7cb0fb7155b9283c4d10180e477f658754595b4dedb249f1e143e899d0e6c
license    : MIT
component  : system.utils
summary    : Version-bump your software with a single command!
description: |
    A small command line tool to simplify releasing software by updating all version strings in your source code by the correct increment.
build      : |
    %python3_setup
install    : |
    %python3_install
